<div class="card">
                            <!--begin::Body-->
                            <div class="card-body p-lg-20">
                                <!--begin::Layout-->
                                <div class="d-flex flex-column flex-xl-row">
                                    <!--begin::Content-->
                                    <div class="flex-lg-row-fluid me-xl-18 mb-10 mb-xl-0">
                                        <!--begin::Head-->
                                        <div class="d-flex flex-stack flex-wrap mb-10 mb-lg-15">
                                            <!--begin::Logo-->
                                            <a href="#">
                                                <img alt="Logo" class="h-50px" src="" />
                                            </a>
                                            <!--end::Logo-->
                                            <!--begin::Actions-->
                                            <div class="my-2">

                                                <a href="#" class="btn btn-sm btn-success">TEST</a>
                                            </div>
                                            <!--end::Actions-->
                                        </div>
                                        <!--end::Head-->
                                        <!--begin::Wrapper-->

                                        <!--end::Wrapper-->
                                    </div>
                                    <div class="m-0">

                                        <div class="d-print-none border border-dashed border-gray-300 card-rounded h-lg-100 min-w-md-350px p-9 bg-lighten">
                                            <!--begin::Labels-->
                                            <div class="mb-8">
                                                <span class="badge badge-light-success me-2">Door</span>
                                                <span class="badge badge-light-warning">List</span>
                                            </div>

                                            <h6 class="mb-8 fw-boldest text-gray-600 text-hover-primary">Extern Doors
                                            </h6>
                                            <div class="mb-8">
                                                <div class="fw-bolder fs-6 text-gray-800 d-flex align-items-center">
                                                    Front Door
                                                    <span class="fs-7 text-success d-flex align-items-center">
                                                        <span class="bullet bullet-dot bg-success mx-2"></span>
                                                        <div class=""> <a href="#" class="btn btn-icon btn-success"><i class="las la-wallet fs me text-right"></i>
                                                                <div class="text-center">ON</div>
                                                            </a>
                                                    </span> <br>
                                                </div>
                                            </div>
                                            <div class="mb-8"></div>
                                            <div class="mb-8">
                                                <div class="fw-bolder fs-6 text-gray-800 d-flex align-items-center">
                                                    Garage Door
                                                    <span class="fs-7 text-success d-flex align-items-center">
                                                        <span class="bullet bullet-dot bg-danger mx-2"></span> <a href="#" class="btn btn-icon btn-danger"><i class="las la-wallet fs me"></i>
                                                            <div class="text-center">OFF</div>
                                                        </a></span>
                                                </div>
                                            </div>

                                        </div>


                                    </div>


                                </div>
                            </div>

                        </div>
