<!DOCTYPE html>

<html lang="en">

<head>
	<base href="">
	<title>UVT e-lab</title>

	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta charset="utf-8" />
	<meta property="og:locale" content="en_US" />
	<link rel="shortcut icon" href="assets/media/logos/favicon.ico" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
	<link href=".public/jsplugins/plugins.css" rel="stylesheet" type="text/css" />
	<link href=".public/jsplugins/style.css" rel="stylesheet" type="text/css" />
	<link rel="icon" href="C:\Users\chaye\OneDrive\Desktop\Essai\logo.jpg">

</head>

<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed aside-fixed aside-secondary-enabled">
	<div class="d-flex flex-column flex-root">
		<div class="page d-flex flex-row flex-column-fluid">
			<div id="kt_aside" class="aside aside-extended bg-white" data-kt-drawer="true" data-kt-drawer-name="aside"
				data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true"
				data-kt-drawer-width="auto" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
				<div class="aside-primary d-flex flex-column align-items-lg-center flex-row-auto">
					<div class="aside-logo d-none d-lg-flex flex-column align-items-center flex-column-auto py-10"
						id="kt_aside_logo">
						<a href="Home&security.html">
							<img alt="Logo" src=".public/logo.jpg" class="h-50px" />
						</a>
					</div>
					<div class="aside-nav d-flex flex-column align-items-center flex-column-fluid w-100 pt-5 pt-lg-0"
						id="kt_aside_nav">
						<div class="hover-scroll-y mb-10" data-kt-scroll="true"
							data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-height="auto"
							data-kt-scroll-wrappers="#kt_aside_nav"
							data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer"
							data-kt-scroll-offset="0px">
							<ul class="nav flex-column">

								<li class="nav-item mb-2" data-bs-toggle="tooltip" data-bs-trigger="hover"
									data-bs-placement="right" data-bs-dismiss="click" title="Tasks">
									<a class="nav-link btn btn-custom btn-icon" data-bs-toggle="tab"
										href="#kt_aside_nav_tab_tasks">
										<span class="svg-icon svg-icon-2x">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
												viewBox="0 0 24 24" fill="none">
												<path opacity="0.3"
													d="M20.5543 4.37824L12.1798 2.02473C12.0626 1.99176 11.9376 1.99176 11.8203 2.02473L3.44572 4.37824C3.18118 4.45258 3 4.6807 3 4.93945V13.569C3 14.6914 3.48509 15.8404 4.4417 16.984C5.17231 17.8575 6.18314 18.7345 7.446 19.5909C9.56752 21.0295 11.6566 21.912 11.7445 21.9488C11.8258 21.9829 11.9129 22 12.0001 22C12.0872 22 12.1744 21.983 12.2557 21.9488C12.3435 21.912 14.4326 21.0295 16.5541 19.5909C17.8169 18.7345 18.8277 17.8575 19.5584 16.984C20.515 15.8404 21 14.6914 21 13.569V4.93945C21 4.6807 20.8189 4.45258 20.5543 4.37824Z"
													fill="black" />
												<path
													d="M10.5606 11.3042L9.57283 10.3018C9.28174 10.0065 8.80522 10.0065 8.51412 10.3018C8.22897 10.5912 8.22897 11.0559 8.51412 11.3452L10.4182 13.2773C10.8099 13.6747 11.451 13.6747 11.8427 13.2773L15.4859 9.58051C15.771 9.29117 15.771 8.82648 15.4859 8.53714C15.1948 8.24176 14.7183 8.24176 14.4272 8.53714L11.7002 11.3042C11.3869 11.6221 10.874 11.6221 10.5606 11.3042Z"
													fill="black" />
											</svg>
										</span>
									</a>
								</li>

								<li class="nav-item mb-2" data-bs-toggle="tooltip" data-bs-trigger="hover"
									data-bs-placement="right" data-bs-dismiss="click" title="Users">
									<a class="nav-link btn btn-custom btn-icon" data-bs-toggle="tab"
										href="#kt_aside_nav_tab_authors">
										<span class="svg-icon svg-icon-2x">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
												viewBox="0 0 24 24" fill="none">
												<path opacity="0.3"
													d="M20 15H4C2.9 15 2 14.1 2 13V7C2 6.4 2.4 6 3 6H21C21.6 6 22 6.4 22 7V13C22 14.1 21.1 15 20 15ZM13 12H11C10.5 12 10 12.4 10 13V16C10 16.5 10.4 17 11 17H13C13.6 17 14 16.6 14 16V13C14 12.4 13.6 12 13 12Z"
													fill="black" />
												<path
													d="M14 6V5H10V6H8V5C8 3.9 8.9 3 10 3H14C15.1 3 16 3.9 16 5V6H14ZM20 15H14V16C14 16.6 13.5 17 13 17H11C10.5 17 10 16.6 10 16V15H4C3.6 15 3.3 14.9 3 14.7V18C3 19.1 3.9 20 5 20H19C20.1 20 21 19.1 21 18V14.7C20.7 14.9 20.4 15 20 15Z"
													fill="black" />
											</svg>
										</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="aside-footer d-flex flex-column align-items-center flex-column-auto"
						id="kt_aside_footer">

						<div class="d-flex align-items-center mb-10" id="kt_header_user_menu_toggle">
							<div class="cursor-pointer symbol symbol-40px" data-kt-menu-trigger="click"
								data-kt-menu-overflow="true" data-kt-menu-placement="top-start" data-bs-toggle="tooltip"
								data-bs-placement="right" data-bs-dismiss="click" title="User profile">
								<img src=".public/avatars/150-26.jpg" alt="image" />
							</div>
							<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-primary fw-bold py-4 fs-6 w-275px"
								data-kt-menu="true">
								<div class="menu-item px-3">
									<div class="menu-content d-flex align-items-center px-3">
										<div class="symbol symbol-50px me-5">
											<img alt="Logo" src=".public/avatars/150-26.jpg" />
										</div>
										<div class="d-flex flex-column">
											<div class="fw-bolder d-flex align-items-center fs-5">User USER
												<span class="badge badge-light-success fw-bolder fs-8 px-2 py-1 ms-2">At
													Home</span>
											</div>

										</div>

									</div>
								</div>

								<div class="separator my-2"></div>

								<div class="menu-item px-5">
									<a href="" class="menu-link px-5">My Profile</a>
								</div>



								<div class="menu-item px-5">
									<a href="#" class="menu-link px-5">My Activities</a>
								</div>
								<div class="separator my-2"></div>

								<div class="menu-item px-5 my-1">
									<a href="#" class="menu-link px-5">Account Settings</a>
								</div>
								<div class="menu-item px-5">
									<a href="#" class="menu-link px-5">Sign Out</a>
								</div>
								<div class="separator my-2"></div>

							</div>
						</div>
					</div>

				</div>

				<div class="aside-secondary d-flex flex-row-fluid">
					<div class="aside-workspace my-5 p-5" id="kt_aside_wordspace">
						<div class="d-flex h-100 flex-column">
							<div class="flex-column-fluid hover-scroll-y" data-kt-scroll="true"
								data-kt-scroll-activate="true" data-kt-scroll-height="auto"
								data-kt-scroll-wrappers="#kt_aside_wordspace"
								data-kt-scroll-dependencies="#kt_aside_secondary_footer" data-kt-scroll-offset="0px">
								<div class="tab-content">

									<div class="tab-pane fade" id="kt_aside_nav_tab_tasks" role="tabpanel">
										<div class="mx-5">
											<h3 class="fw-bolder text-dark mb-10 mx-0">Tasks</h3>

											<div class="mb-12">
												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-success">
															<span class="svg-icon svg-icon-2x svg-icon-success">
																<svg xmlns="" width="24" height="24" viewBox="0 0 24 24"
																	fill="none">
																	<path opacity="0.3"
																		d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z"
																		fill="black" />
																	<path
																		d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z"
																		fill="black" />
																</svg>
															</span>
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="Home&security.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Security
														</a>

													</div>
												</div>
												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-warning">
															<span class="svg-icon svg-icon-2x svg-icon-warning">
																<svg xmlns="" width="24" height="24" viewBox="0 0 24 24"
																	fill="none">
																	<path opacity="0.3"
																		d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z"
																		fill="black" />
																	<path
																		d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z"
																		fill="black" />
																</svg>
															</span>
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="lighting.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Lighting
															System
														</a>

													</div>
												</div>
												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-success">
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="door.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Door
															Controling</a>

													</div>
												</div>
												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-primary">
															<span class="svg-icon svg-icon-2x svg-icon-primary">
																<svg xmlns="" width="24" height="24" viewBox="0 0 24 24"
																	fill="none">
																	<path opacity="0.3"
																		d="M20 3H4C2.89543 3 2 3.89543 2 5V16C2 17.1046 2.89543 18 4 18H4.5C5.05228 18 5.5 18.4477 5.5 19V21.5052C5.5 22.1441 6.21212 22.5253 6.74376 22.1708L11.4885 19.0077C12.4741 18.3506 13.6321 18 14.8167 18H20C21.1046 18 22 17.1046 22 16V5C22 3.89543 21.1046 3 20 3Z"
																		fill="black" />
																	<rect x="6" y="12" width="7" height="2" rx="1"
																		fill="black" />
																	<rect x="6" y="7" width="12" height="2" rx="1"
																		fill="black" />
																</svg>
															</span>
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="climate.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Climate</a>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-danger">
															<span class="svg-icon svg-icon-2x svg-icon-danger">
																<svg xmlns="" width="24" height="24" viewBox="0 0 24 24"
																	fill="none">
																	<path
																		d="M11.2166 8.50002L10.5166 7.80007C10.1166 7.40007 10.1166 6.80005 10.5166 6.40005L13.4166 3.50002C15.5166 1.40002 18.9166 1.50005 20.8166 3.90005C22.5166 5.90005 22.2166 8.90007 20.3166 10.8001L17.5166 13.6C17.1166 14 16.5166 14 16.1166 13.6L15.4166 12.9C15.0166 12.5 15.0166 11.9 15.4166 11.5L18.3166 8.6C19.2166 7.7 19.1166 6.30002 18.0166 5.50002C17.2166 4.90002 16.0166 5.10007 15.3166 5.80007L12.4166 8.69997C12.2166 8.89997 11.6166 8.90002 11.2166 8.50002ZM11.2166 15.6L8.51659 18.3001C7.81659 19.0001 6.71658 19.2 5.81658 18.6C4.81658 17.9 4.71659 16.4 5.51659 15.5L8.31658 12.7C8.71658 12.3 8.71658 11.7001 8.31658 11.3001L7.6166 10.6C7.2166 10.2 6.6166 10.2 6.2166 10.6L3.6166 13.2C1.7166 15.1 1.4166 18.1 3.1166 20.1C5.0166 22.4 8.51659 22.5 10.5166 20.5L13.3166 17.7C13.7166 17.3 13.7166 16.7001 13.3166 16.3001L12.6166 15.6C12.3166 15.2 11.6166 15.2 11.2166 15.6Z"
																		fill="black" />
																	<path opacity="0.3"
																		d="M5.0166 9L2.81659 8.40002C2.31659 8.30002 2.0166 7.79995 2.1166 7.19995L2.31659 5.90002C2.41659 5.20002 3.21659 4.89995 3.81659 5.19995L6.0166 6.40002C6.4166 6.60002 6.6166 7.09998 6.5166 7.59998L6.31659 8.30005C6.11659 8.80005 5.5166 9.1 5.0166 9ZM8.41659 5.69995H8.6166C9.1166 5.69995 9.5166 5.30005 9.5166 4.80005L9.6166 3.09998C9.6166 2.49998 9.2166 2 8.5166 2H7.81659C7.21659 2 6.71659 2.59995 6.91659 3.19995L7.31659 4.90002C7.41659 5.40002 7.91659 5.69995 8.41659 5.69995ZM14.6166 18.2L15.1166 21.3C15.2166 21.8 15.7166 22.2 16.2166 22L17.6166 21.6C18.1166 21.4 18.4166 20.8 18.1166 20.3L16.7166 17.5C16.5166 17.1 16.1166 16.9 15.7166 17L15.2166 17.1C14.8166 17.3 14.5166 17.7 14.6166 18.2ZM18.4166 16.3L19.8166 17.2C20.2166 17.5 20.8166 17.3 21.0166 16.8L21.3166 15.9C21.5166 15.4 21.1166 14.8 20.5166 14.8H18.8166C18.0166 14.8 17.7166 15.9 18.4166 16.3Z"
																		fill="black" />
																</svg>
															</span>
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="data.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Data
															Reveiw</a>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<span class="symbol-label bg-light-info">
															<span class="svg-icon svg-icon-2x svg-icon-info">
																<svg xmlns="" width="24" height="24" viewBox="0 0 24 24"
																	fill="none">
																	<path opacity="0.3"
																		d="M20.5543 4.37824L12.1798 2.02473C12.0626 1.99176 11.9376 1.99176 11.8203 2.02473L3.44572 4.37824C3.18118 4.45258 3 4.6807 3 4.93945V13.569C3 14.6914 3.48509 15.8404 4.4417 16.984C5.17231 17.8575 6.18314 18.7345 7.446 19.5909C9.56752 21.0295 11.6566 21.912 11.7445 21.9488C11.8258 21.9829 11.9129 22 12.0001 22C12.0872 22 12.1744 21.983 12.2557 21.9488C12.3435 21.912 14.4326 21.0295 16.5541 19.5909C17.8169 18.7345 18.8277 17.8575 19.5584 16.984C20.515 15.8404 21 14.6914 21 13.569V4.93945C21 4.6807 20.8189 4.45258 20.5543 4.37824Z"
																		fill="black" />
																	<path
																		d="M12.0006 11.1542C13.1434 11.1542 14.0777 10.22 14.0777 9.0771C14.0777 7.93424 13.1434 7 12.0006 7C10.8577 7 9.92348 7.93424 9.92348 9.0771C9.92348 10.22 10.8577 11.1542 12.0006 11.1542Z"
																		fill="black" />
																	<path
																		d="M15.5652 13.814C15.5108 13.6779 15.4382 13.551 15.3566 13.4331C14.9393 12.8163 14.2954 12.4081 13.5697 12.3083C13.479 12.2993 13.3793 12.3174 13.3067 12.3718C12.9257 12.653 12.4722 12.7981 12.0006 12.7981C11.5289 12.7981 11.0754 12.653 10.6944 12.3718C10.6219 12.3174 10.5221 12.2902 10.4314 12.3083C9.70578 12.4081 9.05272 12.8163 8.64456 13.4331C8.56293 13.551 8.49036 13.687 8.43595 13.814C8.40875 13.8684 8.41781 13.9319 8.44502 13.9864C8.51759 14.1133 8.60828 14.2403 8.68991 14.3492C8.81689 14.5215 8.95295 14.6757 9.10715 14.8208C9.23413 14.9478 9.37925 15.0657 9.52439 15.1836C10.2409 15.7188 11.1026 15.9999 11.9915 15.9999C12.8804 15.9999 13.7421 15.7188 14.4586 15.1836C14.6038 15.0748 14.7489 14.9478 14.8759 14.8208C15.021 14.6757 15.1661 14.5215 15.2931 14.3492C15.3838 14.2312 15.4655 14.1133 15.538 13.9864C15.5833 13.9319 15.5924 13.8684 15.5652 13.814Z"
																		fill="black" />
																</svg>
															</span>
														</span>
													</div>

													<div class="d-flex flex-column">
														<a href="model.html"
															class="text-gray-800 text-hover-primary fs-6 fw-bold">Add a
															new model
														</a>

													</div>
												</div>

											</div>
										</div>
									</div>

									<div class="tab-pane fade" id="kt_aside_nav_tab_authors" role="tabpanel">
										<div class="mx-5">
											<h3 class="fw-bolder text-dark mx-0 mb-10">Users</h3>

											<div class="mb-12">
												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<img src=".public/avatars/150-1.jpg" class="" alt="" />
													</div>

													<div class="flex-grow-1">
														<p class="text-dark fw-bolder text-hover-primary fs-6">User 1
														</p>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<img src=".public/avatars/150-4.jpg" class="" alt="" />
													</div>

													<div class="flex-grow-1">
														<p class="text-dark fw-bolder text-hover-primary fs-6">User 2
														</p>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<img src=".public/avatars/150-12.jpg" class="" alt="" />
													</div>

													<div class="flex-grow-1">
														<p class="text-dark fw-bolder text-hover-primary fs-6">User 3
														</p>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<img src=".public/avatars/150-6.jpg" class="" alt="" />
													</div>

													<div class="flex-grow-1">
														<p class="text-dark fw-bolder text-hover-primary fs-6">user 4
														</p>

													</div>
												</div>

												<div class="d-flex align-items-center mb-7">
													<div class="symbol symbol-50px me-5">
														<img src=".public/avatars/150-9.jpg" class="" alt="" />
													</div>

													<div class="flex-grow-1">
														<p class="text-dark fw-bolder text-hover-primary fs-6">User 5
														</p>

													</div>
												</div>

											</div>
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>

				<button
					class="btn btn-sm btn-icon bg-body btn-color-gray-600 btn-active-primary position-absolute translate-middle start-100 end-0 bottom-0 shadow-sm d-none d-lg-flex"
					data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body"
					data-kt-toggle-name="aside-minimize" style="margin-bottom: 1.35rem">

				</button>
			</div>
			<div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
				<div id="kt_header" class="header" data-kt-sticky="true" data-kt-sticky-name="header"
					data-kt-sticky-offset="{default: '200px', lg: '300px'}">
					<div class="container-xxl d-flex align-items-center justify-content-between"
						id="kt_header_container">
						<div class="page-title d-flex flex-column align-items-start justify-content-center flex-wrap me-lg-2 pb-5 pb-lg-0"
							data-kt-swapper="true" data-kt-swapper-mode="prepend"
							data-kt-swapper-parent="{default: '#kt_content_container', lg: '#kt_header_container'}">
							<h1 class="text-dark fw-bold my-0 fs-2">Dashboard </h1>
							<ul class="breadcrumb breadcrumb-line text-muted fw-bold fs-base my-1">
								<li class="breadcrumb-item text-muted">
									<a href="../dist/index.html" class="text-muted">E-lab </a>
								</li>
								<li class="breadcrumb-item text-dark">Security</li>
							</ul>
						</div>

					</div>
				</div>
				<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
					<div class="container-xxl" id="kt_content_container">
						<div class="row gy-5 g-xl-8">
							<div class="col-xl-8">
								<div class="card card-xl-stretch mb-5 mb-xl-8">

									<div class="card-header border-0 pt-5">
										<h3 class="card-title align-items-start flex-column">
											<span class="card-label fw-bolder fs-3 mb-1">Camera</span>
											<span class="text-muted fw-bold fs-7">Security</span>
										</h3>
									</div>
									<table class="table table-bordered align-middle mb-0 bg-white" widht="100%"
										cellspacing="0" id="dataTable">
										<thead class="text-center">
											<tr>
												<th class="text-center">Camera</th>
												<th class="text-center">Statut</th>
												<th class="text-center">Action</th>
											</tr>

										</thead>
										<tbody class="text-center">
											<tr class="text-center">
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class=" btn btn-secondary btn-icon-split">

																	<span class="text">Front Door</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span class="badge badge-success rounded-pill d-inline">ON</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark" data-bs-toggle="modal"
														data-bs-target="#exampleModalCenter">
														View
													</button>
													<div class="modal fade" id="exampleModalCenter" tabindex="-1"
														role="dialog" aria-labelledby="exampleModalCenterTitle"
														aria-hidden="true">
														<div class="modal-dialog modal-dialog-centered" role="document">
															<div class="modal-content">
																<div class="modal-header">
																	<h5 class="modal-title" id="exampleModalLongTitle">
																		Fonrt Door Camera</h5>
																	<button type="button" class="close"
																		data-bs-dismiss="modal" aria-label="Close">
																		<span aria-hidden="true">&times;</span>
																	</button>
																</div>
																<div class="modal-body">
																	Camera opened
																</div>
																<div class="modal-footer">
																	<button type="button" class="btn btn-secondary"
																		data-bs-dismiss="modal">Close</button>

																</div>
															</div>
														</div>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class="btn btn-secondary btn-icon-split">

																	<span class="text">Kitchen</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span class="badge badge-dark rounded-pill d-inline">OFF</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark" data-bs-toggle="modal"
														data-bs-target="#exampleModalCenter1">
														View
													</button>
													<div class="modal fade" id="exampleModalCenter1" tabindex="-1"
														role="dialog" aria-labelledby="exampleModalCenterTitle"
														aria-hidden="true">
														<div class="modal-dialog modal-dialog-centered" role="document">
															<div class="modal-content">
																<div class="modal-header">
																	<h5 class="modal-title" id="exampleModalLongTitle">
																		Fonrt Door Camera</h5>
																	<button type="button" class="close"
																		data-bs-dismiss="modal" aria-label="Close">
																		<span aria-hidden="true">&times;</span>
																	</button>
																</div>
																<div class="modal-body">
																	Camera closed
																</div>
																<div class="modal-footer">
																	<button type="button" class="btn btn-secondary"
																		data-bs-dismiss="modal">Close</button>

																</div>
															</div>
														</div>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class="btn btn-secondary btn-icon-split">

																	<span class="text">Living Room</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span
														class="badge badge-danger rounded-pill d-inline">Disconnected</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark" data-bs-toggle="modal"
														data-bs-target="#exampleModalCenter2">
														View
													</button>
													<div class="modal fade" id="exampleModalCenter2" tabindex="-1"
														role="dialog" aria-labelledby="exampleModalCenterTitle"
														aria-hidden="true">
														<div class="modal-dialog modal-dialog-centered" role="document">
															<div class="modal-content">
																<div class="modal-header">
																	<h5 class="modal-title" id="exampleModalLongTitle">
																		Fonrt Door Camera</h5>
																	<button type="button" class="close"
																		data-bs-dismiss="modal" aria-label="Close">
																		<span aria-hidden="true">&times;</span>
																	</button>
																</div>
																<div class="modal-body">
																	Camera Not conected
																</div>
																<div class="modal-footer">
																	<button type="button" class="btn btn-secondary"
																		data-bs-dismiss="modal">Close</button>

																</div>
															</div>
														</div>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class="btn btn-secondary btn-icon-split">

																	<span class="text">Kids Room</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span
														class="badge badge-danger rounded-pill d-inline">Disconnected</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark">
														View
													</button>
												</td>
											</tr>
											<tr>
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class="btn btn-secondary btn-icon-split">

																	<span class="text">Kitchen</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span
														class="badge badge-danger rounded-pill d-inline">Disconnected</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark">
														View
													</button>
												</td>
											</tr>
											<tr>
												<td>
													<div class="d-flex align-items-center">

														<div class="ms-3">
															<p class="fw-bold mb-1"><a href="#"
																	class="btn btn-secondary btn-icon-split">

																	<span class="text">Bed Room</span>
																</a> </p>

														</div>
													</div>
												</td>

												<td>
													<span
														class="badge badge-danger rounded-pill d-inline">Disconnected</span>
												</td>

												<td>
													<button type="button"
														class="btn btn-link btn-rounded btn-sm fw-bold"
														data-mdb-ripple-color="dark">
														View
													</button>
												</td>
											</tr>
										</tbody>
									</table>


								</div>
							</div>

							<div class="col-xl-4">
								<div class="card card-xl-stretch mb-5 mb-xl-8">
									<div class="card-header border-0 bg-primary py-5">
										<h3 class="card-title fw-bolder text-white">Alarm</h3>

									</div>
									<div class="card-body p-0">
										Protected
										<div class=" text-center  bg-body mt-n10 position-relative card-px py-15">
											<img class="img-fluid" src=".public/checked.png"
												alt=""><br> <br>

											<h3 class="text-success">Protected !</h3> <br>
											<button type="button"
												class="btn btn-danger btn-lg">Desactivate</button><br><br>
											<button type="button" class="btn btn-warning btn-sm">Emergency
												Call!</button>

										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row gy-5 g-xl-8">
							<div class="col-xl-8">
								<div class="card card-xl-stretch mb-5 mb-xl-8">
									<div class="card-header border-0 pt-5">
										<h3 class="card-title align-items-start flex-column">
											<span class="card-label fw-bolder fs-3 mb-1">User Access</span>

										</h3>

									</div>
									<div class="card-body py-3">
										<div class="table-responsive">
											<table
												class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
												<thead>
													<tr class="fw-bolder text-muted">
														<th class="w-25px">
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input" type="checkbox"
																	value="1" data-kt-check="true"
																	data-kt-check-target=".widget-9-check" />
															</div>
														</th>
														<th class="min-w-150px">Authors</th>
														<th class="min-w-140px">Time</th>
														<th class="min-w-120px">Premssion</th>
														<th class="min-w-100px text-end">Actions</th>
													</tr>
												</thead>

												<tbody>
													<tr>
														<td>
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input widget-9-check"
																	type="checkbox" value="1" />
															</div>
														</td>
														<td>
															<div class="d-flex align-items-center">
																<div class="symbol symbol-45px me-5">
																	<img src=".public/avatars/150-11.jpg" alt="" />
																</div>
																<div class="d-flex justify-content-start flex-column">
																	<a href="#"
																		class="text-dark fw-bolder text-hover-primary fs-6">User
																		1
																	</a>

																</div>
															</div>
														</td>
														<td>
															<h5><time datetime="2023-06-15T20:00:00">20:00</time></h5>
														</td>
														<td class="text-end">
															<div class="d-flex flex-column w-100 me-2">
																<div class="d-flex flex-stack mb-2">
																	<span class="text-muted me-2 fs-7 fw-bold"><i
																			class=" d-inline text-success bi bi-check-circle-fill"></i>
																		<p class=" d-inline text-success"> Garanted</p>
																	</span>
																</div>

														</td>

													</tr>
													<tr>
														<td>
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input widget-9-check"
																	type="checkbox" value="1" />
															</div>
														</td>
														<td>
															<div class="d-flex align-items-center">
																<div class="symbol symbol-45px me-5">
																	<img src=".public/avatars/150-3.jpg" alt="" />
																</div>
																<div class="d-flex justify-content-start flex-column">
																	<a href="#"
																		class="text-dark fw-bolder text-hover-primary fs-6">user
																		2
																	</a>

																</div>
															</div>
														</td>
														<td>
															<h5><time datetime="2023-06-15T20:00:00">16:00</time></h5>
														</td>
														<td class="text-end">
															<div class="d-flex flex-stack mb-2">
																<span class="text-muted me-2 fs-7 fw-bold"><i
																		class=" d-inline text-success bi bi-check-circle-fill"></i>
																	<p class=" d-inline text-success"> Garanted</p>
																</span>
															</div>
														</td>

													</tr>
													<tr>
														<td>
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input widget-9-check"
																	type="checkbox" value="1" />
															</div>
														</td>
														<td>
															<div class="d-flex align-items-center">
																<div class="symbol symbol-45px me-5">
																	<img src=".public/avatars/150-4.jpg" alt="" />
																</div>
																<div class="d-flex justify-content-start flex-column">
																	<a href="#"
																		class="text-dark fw-bolder text-hover-primary fs-6">Guest
																	</a>

																</div>
															</div>
														</td>
														<td>
															<h5><time datetime="2023-06-15T20:00:00">01:00</time></h5>
														</td>
														<td class="text-end">
															<div class="d-flex flex-column w-100 me-2">
																<div class="d-flex flex-stack mb-2">
																	<span class="text-muted me-2 fs-7 fw-bold"><i
																			class=" d-inline text-danger bi bi-check-circle-fill"></i>
																		<p class=" d-inline text-danger"> Denied</p>
																	</span>
																</div>
															</div>
														</td>

													</tr>
													<tr>
														<td>
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input widget-9-check"
																	type="checkbox" value="1" />
															</div>
														</td>
														<td>
															<div class="d-flex align-items-center">
																<div class="symbol symbol-45px me-5">
																	<img src=".public/avatars/150-5.jpg" alt="" />
																</div>
																<div class="d-flex justify-content-start flex-column">
																	<a href="#"
																		class="text-dark fw-bolder text-hover-primary fs-6">Unknown
																	</a>

																</div>
															</div>
														</td>
														<td>
															<h5><time datetime="2023-06-15T20:00:00">01:00</time></h5>
														</td>
														<td class="text-end">
															<div class="d-flex flex-column w-100 me-2">
																<div class="d-flex flex-stack mb-2">
																	<span class="text-muted me-2 fs-7 fw-bold"><i
																			class=" d-inline text-danger bi bi-check-circle-fill"></i>
																		<p class=" d-inline text-danger"> Denied</p>
																	</span>
																</div>
															</div>
														</td>

													</tr>
													<tr>
														<td>
															<div
																class="form-check form-check-sm form-check-custom form-check-solid">
																<input class="form-check-input widget-9-check"
																	type="checkbox" value="1" />
															</div>
														</td>
														<td>
															<div class="d-flex align-items-center">
																<div class="symbol symbol-45px me-5">
																	<img src=".public/avatars/150-6.jpg" alt="" />
																</div>
																<div class="d-flex justify-content-start flex-column">
																	<a href="#"
																		class="text-dark fw-bolder text-hover-primary fs-6">Unknown
																	</a>

																</div>
															</div>
														</td>
														<td>
															<h5><time datetime="2023-06-15T20:00:00">02:00</time></h5>
														</td>
														<td class="text-end">
															<div class="d-flex flex-column w-100 me-2">
																<div class="d-flex flex-stack mb-2">
																	<span class="text-muted me-2 fs-7 fw-bold"><i
																			class=" d-inline text-danger bi bi-check-circle-fill"></i>
																		<p class=" d-inline text-danger"> Denied</p>
																	</span>
																</div>
															</div>
														</td>
														<td></td>
														<td>
															<div class="d-flex flex-column w-100 me-2">
																<div class="d-flex flex-stack mb-2">
																	<span class="text-muted me-2 fs-7 fw-bold"><i
																			class=" d-inline text-danger bi bi-check-circle-fill"></i>
																		<p class=" d-inline text-info"> Check Camera</p>
																	</span>
																</div>
														</td>

													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
							<div class="col-xl-4">
								<div class="card card-xl-stretch mb-5 mb-xl-8">
									<div class="card-header border-0 pt-5">
										<h3 class="card-title align-items-start flex-column">
											<span class="card-label fw-bolder text-dark">Door Controling</span>

										</h3>

									</div>

									<div class="card-body pt-5">
										<div class="d-flex align-items-sm-center mb-7">
											<div class="symbol symbol-50px me-5">
												<span class="symbol-label">
													<i class="bi bi-door-open-fill"></i>
												</span>
											</div>

											<div class="d-flex align-items-center flex-row-fluid flex-wrap">
												<div class="flex-grow-1 me-2">
													<h3 class=""> Front Door</h3>
												</div>
												<div class=" badge badge-light fw-bolder my-2 form-check form-switch">
													<input class="form-check-input" type="checkbox"
														id="flexSwitchCheckDefault">

												</div>

											</div>
										</div>

										<div class="d-flex align-items-sm-center mb-7">

											<div class="symbol symbol-50px me-5">
												<span class="symbol-label">
													<i class="bi bi-door-open-fill"></i>

												</span>
											</div>

											<div class="d-flex align-items-center flex-row-fluid flex-wrap">
												<div class="flex-grow-1 me-2">
													<h3 class=""> Garage Door</h3>
												</div>
												<div class=" badge badge-light fw-bolder my-2 form-check form-switch">
													<input class="form-check-input" type="checkbox"
														id="flexSwitchCheckDefault">

												</div>
											</div>

										</div>

										<div class="d-flex align-items-sm-center mb-7">
											<div class="symbol symbol-50px me-5">
												<span class="symbol-label">
													<i class="bi bi-door-open-fill"></i>

												</span>
											</div>

											<div class="d-flex align-items-center flex-row-fluid flex-wrap">
												<div class="flex-grow-1 me-2">
													<h3 class=""> Kids Room Door</h3>
												</div>
												<div class=" badge badge-light fw-bolder my-2 form-check form-switch">
													<input class="form-check-input" type="checkbox"
														id="flexSwitchCheckDefault">

												</div>
											</div>
										</div>

										<div class="d-flex align-items-sm-center mb-7">
											<div class="symbol symbol-50px me-5">
												<span class="symbol-label">
													<i class="bi bi-door-open-fill"></i>

												</span>
											</div>

											<div class="d-flex align-items-center flex-row-fluid flex-wrap">
												<div class="flex-grow-1 me-2">
													<h3 class=""> Living Room Door</h3>
												</div>
												<div class=" badge badge-light fw-bolder my-2 form-check form-switch">
													<input class="form-check-input" type="checkbox"
														id="flexSwitchCheckDefault">

												</div>
											</div>

										</div>

										<div class="d-flex align-items-sm-center mb-7">
											<div class="d-flex align-items-sm-center mb-7">
												<div class="symbol symbol-50px me-5">
													<span class="symbol-label">
														<i class="bi bi-door-open-fill"></i>

													</span>
												</div>

												<div class="d-flex align-items-center flex-row-fluid flex-wrap">
													<div class="flex-grow-1 me-2">
														<h3 class=""> Elevator Door</h3>
													</div>
													<div
														class=" badge badge-light fw-bolder my-2 form-check form-switch">
														<input class="form-check-input" type="checkbox"
															id="flexSwitchCheckDefault">

													</div>
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
				<div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
					<div class="container-xxl d-flex flex-column flex-md-row flex-stack">
						<div class="text-dark order-2 order-md-1">
							<span class="text-gray-400 fw-bold me-1">Created by Hamza And Sabeur</span>

						</div>


					</div>
				</div>
			</div>
		</div>
	</div>

	<script>var hostUrl = "assets/";</script>
	<script src="./public/jsplugins/pluginelab.js"></script>
	<script src="./public/jsplugins/scriptelab.js"></script>
	<script src="./public/jsplugins/widgets.js"></script>
</body>

</html>